apiVersion: v1
kind: Secret
metadata:
  name: socialboom-secrets
  namespace: socialboom
type: Opaque
stringData:
  # In a real CI/CD pipeline, these values would be injected dynamically from Azure Key Vault or GitHub Secrets
  jwt-secret-key: "supersecretjwtkeythatshouldbechangedinprod"
  postgres-password: "password"
  
  # Full Database Connection Strings
  user-db-url: "postgresql+psycopg://postgres:password@postgres:5432/testing"
  booking-db-url: "postgresql+psycopg://postgres:password@postgres:5432/bookingsdb"
  notification-db-url: "postgres://postgres:password@postgres:5432/notificationsdb?sslmode=disable"
